CREATE TABLE OFFERS (
  ID                 BIGINT NOT NULL,
  VERSION            VARCHAR(50),
  YEAR_OF_PRODUCTION INTEGER,
  POWER              VARCHAR(50),
  FUEL_TYPE          VARCHAR(50),
  PROVINCE           VARCHAR(50),
  MILEAGE            INTEGER,
  PRICE              INTEGER
);